"use client";
import { rootReducer } from "@/store/Reducers/rootReducer";
import { Inter } from "next/font/google";
import { QueryClient, QueryClientProvider } from "react-query";
import { Provider } from "react-redux";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { applyMiddleware, compose, createStore } from "redux";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Share A Video",
//   description: "Generated by create next app",
// };

// const composeEnhancers =
//   (window as any).__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;
// const store = createStore(rootReducer, composeEnhancers(applyMiddleware())); // Tạo Redux store bằng cách sử dụng hàm createStore và truyền vào rootReducer.
const store = createStore(rootReducer);
const queryClient = new QueryClient(); // Tạo một instance của QueryClient để quản lý trạng thái của các truy vấn.

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="https://www.iconpacks.net/icons/2/free-youtube-logo-icon-2431-thumb.png"
          type="image/png"
        />
      </head>
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
          <Provider store={store}>{children}</Provider>
          <ToastContainer />
        </QueryClientProvider>
      </body>
    </html>
  );
}
